### ISSUE TITLE
Nested lists with word wrap don't indent subsequent lines properly in editor mode

### ISSUE THREAD

**Issue by Esras** [insanum/obsidian_gruvbox#11]
When generating a nested list in edit mode with word wrapped turned on, lines that are nested beyond the first level have an incorrect indentation:

![Screenshot from 2021-01-30 17-39-57](https://user-images.githubusercontent.com/9629833/106372197-3e49e480-6322-11eb-961b-bc49da6ce0a6.png)

Playing around with the CSS, the place that seems to cause this is the `font-family: var(--font-monospace)` setting. Removing that (and thus using whatever font is inherited, which in this case is not monospaced) indents properly, but using a non-monospaced font is undesirable.

Note that it is indented incorrectly on even the first layer of indents, it's just close enough to fool at a glance. Relevant CSS tags seem to be `HyperMD-list-line-#` and `cm-list-#`.

**Comment by arthurmarquesv** [comment]
I'm having this problem to. It's annoying because it breaks my list's relationship lines:
 
![image](https://user-images.githubusercontent.com/78812600/107761717-98777c00-6d0a-11eb-99fd-133ca49fae07.png)

Although the indentation is corrected in preview mode, the lines are still broken there, probably because of the problem in edit mode: 

![image](https://user-images.githubusercontent.com/78812600/107762141-53a01500-6d0b-11eb-80c5-9312c69f43ff.png)

**Comment by Ampa** [comment]
Came to report the same issue.

Any chance of a fix?

**Comment by insanum** [comment]
Probably a padding/margin issue. Is this issue only seen in gruvbox? What about the default theme (or others)?

**Comment by Esras** [comment]
I opened https://forum.obsidian.md/t/indentation-in-lists-with-wrapping-at-wrong-depth/17666 about it, but it got pushed to the bug graveyard because a reload after the change to monospaced fonts in the default theme seems to recalculate the indent and fix itself.

**Comment by Ampa** [comment]
The issue was present in Vileplume (my other favorite theme). I raised the issue with the designer, and they managed to fix the issue.

https://github.com/hungsu/vileplume-obsidian/issues/4

**Comment by sanhuesoft** [comment]
[Same issue](https://imgur.com/3Ccrp2Y) around here. It's so annoying.

**Comment by insanum** [comment]
Fixed. This was a pain. :-)
