### ISSUE TITLE
Feature request: Enable font ligatures

### ISSUE THREAD

**Issue by jaideeprana** [insanum/obsidian_gruvbox#15]
This theme is almost perfect for me, except the fact that it lacks font ligratures.

Is there a way to add it in the next release or can you share a way for me to customise gruvbox to support it?

**Comment by tallguyjenks** [comment]
you just need to add a font that supports ligatures. Like Fira Code. 

Under the `body` selector, you can set the font to Fira Code as long as it's installed on your system and it should display ligatures:

```css
body {
    font-family: 'fira code';
}
```

https://fonts.google.com/specimen/Fira+Code

**Comment by tallguyjenks** [comment]
did you try the above example?

**Comment by jaideeprana** [comment]
When I downloaded the Fira code from the link you mentioned it started working :).

Thanks for your help :)

**Comment by jaideeprana** [comment]
Sorry it didn't work, I accidentally checked in a different theme.
