### ISSUE TITLE
empty-state-action items get a purple tint on hover instead of interactive accent color from the theme

### ISSUE THREAD

**Issue by seewishnew** [insanum/obsidian_gruvbox#17]
As the following image shows the hover action for the empty-state-action items are highlighted purple instead of something in alignment with the theme 
![image](https://user-images.githubusercontent.com/14972559/131202512-a432b578-ce7d-4711-b25f-68c805032303.png)

**Comment by insanum** [comment]
Thanks for the pull request! :-)
