### ISSUE TITLE
Indentation in code blocks is weird/broken

### ISSUE THREAD

**Issue by gimbo** [insanum/obsidian_gruvbox#2]
Code block indentation seems broken. E.g. consider the following screenshot using the default theme:

![Screenshot 2020-05-29 at 00 30 06](https://user-images.githubusercontent.com/133770/83204517-f1cf5900-a143-11ea-9ad5-bdf5b1890d00.png)

Here's how this looks if I switch on the gruvbox theme:

![Screenshot 2020-05-29 at 00 30 33](https://user-images.githubusercontent.com/133770/83204495-e5e39700-a143-11ea-9d99-221d8c07ba6e.png)

The indentation levels seem to change as I zoom in/out (e.g. via the View menu)  — very odd.

Other themes I've tried didn't have this issue.

OS: MacOS 10.14.6
Obsidian: 0.6.4
Gruvbox theme: 4e3e34b4af9c6024a92e6b9adda4cb804b88238f

Other than this, loving the theme — very well organised so I can tweak colours, etc. very easily. Thanks!

**Comment by insanum** [comment]
I couldn't repro the exact behavior you're seeing exactly but I definitely see issues with weird indentation in code blocks.

Can you please try this small tweak and let me know if it works? With gruvbox CSS installed edit the obsidian.css file and comment out (or delete) line 179 in the `.HyperMD-codeblock` section which tweaks `padding-left`.

**Comment by gimbo** [comment]
That seems to fix it, yes:

![Screenshot 2020-05-29 at 09 19 23](https://user-images.githubusercontent.com/133770/83237910-88743800-a18d-11ea-92f7-48a4f92e2ebb.png)

**Comment by insanum** [comment]
Great thanks for testing! :-)
