### ISSUE TITLE
FR: add H6 and make heading sizes scale with text

### ISSUE THREAD

**Issue by rubaboo** [insanum/obsidian_gruvbox#20]
Thanks for a great theme, I like different heading colors. Could you add a distinct styling for H6. Also I find the headings too big compared to regular text size, and they don't change size when I change Settings > Appearance > Font size. If you could define them using `em` sizes instead of absolute (if that's what it takes, IDK).

**Comment by insanum** [comment]
Fixed. Thanks for reporting this. :-)
You might still find the header size too big. From h6 up I increased the size by .2em. You can override this in an Obsidian CSS snippet.
