### ISSUE TITLE
Oversized headers issue still persisting on mobile 

### ISSUE THREAD

**Issue by HarStu** [insanum/obsidian_gruvbox#25]
Issue #22 (oversized headers in editing mode) is still occurring on the obsidian mobile app, even while working as intended on desktop

![image](https://user-images.githubusercontent.com/33430956/157712011-2db058ba-4487-45f3-91ab-06887478d871.png)
![image](https://user-images.githubusercontent.com/33430956/157712120-c699128b-15da-4ca6-a31f-e243928eecfc.png)

I'm using version 1.1.0 of the iPad app (issue also applies on iPhone) and the latest update of the theme under "community themes"

**Comment by insanum** [comment]
Theme has been rewritten for Obsidian 0.16.
