### ISSUE TITLE
escaped character recoloured

### ISSUE THREAD

**Issue by jimius** [insanum/obsidian_gruvbox#28]
When escaping the > character with a backslash to prevent a quote block. The > turns gray.
The > renders properly if it's not in the beginning of a sentence but if the > is escaped mid-sentence it turns gray again.
This does not happen in the default theme.

![image](https://user-images.githubusercontent.com/2431118/170466890-4c3a2e5a-fbc3-45b7-97dc-6aaa96126f47.png)

**Comment by insanum** [comment]
Theme has been rewritten for Obsidian 0.16.
