### ISSUE TITLE
Contrast issues in Obsidian 1.0

### ISSUE THREAD

**Issue by HarStu** [insanum/obsidian_gruvbox#32]
Hi,

I've been using this theme for several months, and just got the Obsidian 1.0 update yesterday. After updating, I'm finding it difficult to distinguish between links to existing and non-existing notes.

I don't have any screenshots pre-1.0/0.16, but it was very apparent then: now, I'm struggling to make out the difference at a glance.
![LinkContrast](https://user-images.githubusercontent.com/33430956/195876667-ab95d028-cf3f-4a86-8b3f-f37f5b4b33b4.png)

This is even more of an issue in tables, which have a more "washed out" appearance now. I can barely see the difference between my existing "Rhetoric & Relations" link and my nonexistent "Arts & Recreation" one
![TableContrast](https://user-images.githubusercontent.com/33430956/195876670-65bed8fe-e86f-480b-9f57-5406b8088301.png)

While I'm aware the theme was fully re-written for the 0.16 previews that led up to 1.0, I never had access to the 0.16 previews. As such, I'm unsure if this is a new issue or if these colours are intended. If they are intended, please let me know so I can start figuring out how to fix it for myself with a CSS snippet. Thanks!

**Comment by insanum** [comment]
The accent colors for the existing/non-existing links is a by-product of the new Obsidian default theming. The default theme has the same "hard to distinguish" coloring except for purple on black is a bit easier to distinguish. You can control the fading/alpha level of these links with a snippet.

I agree the row coloring on tables is a bit too extreme. I'll work in this and provide a tweak in the next release.
