### ISSUE TITLE
(FR) Please bring back the orange color for Obsidian V1+

### ISSUE THREAD

**Issue by F3000** [insanum/obsidian_gruvbox#33]
The new "red" color for the main buttons are difficult to see when iOS Darkmode is enabled . 

![image](https://user-images.githubusercontent.com/8161283/195921155-a2890a65-15c3-4986-bf13-bcbb18103d57.png)

Here is the old view : 

![image](https://user-images.githubusercontent.com/8161283/195921176-813e1bb5-5b02-41a2-9e78-e20a7afcbc40.png)

**Comment by insanum** [comment]
On my iOS device the contrast isn't bad at all. I think it looks really good on mobile.

Mostly, the change you're referring to here is more of a by-product of the new Obsidian design. The default theme uses the same color scheme for the icon (just obviously a different palette). You can easily change the icon colors with a snippet.
