### ISSUE TITLE
Cursor position at the beginning of a bullet or numbered list is in the wrong position

### ISSUE THREAD

**Issue by Esras** [insanum/obsidian_gruvbox#36]
Hello again!

When using bulleted or numbered lists, the cursor position appears to be halfway between the end of the bullet or number and the start of the text. I keep thinking that this is a space that I need to delete instead of the space that makes the Markdown work.

This is in the live preview mode.

Images giving examples:

![image](https://user-images.githubusercontent.com/9629833/204039554-5fbd948f-24e3-4f7a-900f-75bf464c1dc5.png)

![image](https://user-images.githubusercontent.com/9629833/204039606-348ef6a9-7c2e-40c0-8923-09e54a1bf6bb.png)

Thank you so much for the theme and keeping it updated - this has been my favorite theme by far!

**Comment by insanum** [comment]
Fixed!
