### ISSUE TITLE
Adding colored number sign

### ISSUE THREAD

**Issue by aethnae** [insanum/obsidian_gruvbox#37]
It would be nice to add a feature that would color the hash signs in editing mode, depending on what header size you're currently in. ([this theme has this feature for example](https://github.com/nickmilo/Cybertron))
Eventhough it's a really minor style feature, it helps using the same header size for multiple paragraphs.

Thanks:)

**Comment by insanum** [comment]
With the new Obsidian 1.0 version all the CSS changed and themes were rewritten. I like how the hashes are a different color vs the heading text. Even though the hash colors don't change, the heading colors do.
