### ISSUE TITLE
Vim cursor shows 'behind' code

### ISSUE THREAD

**Issue by Grazfather** [insanum/obsidian_gruvbox#4]
![Obsidian_v0_7_6_-_notes](https://user-images.githubusercontent.com/497310/87819131-fa313f80-c828-11ea-859d-2c47e8c73376.png)

**Comment by insanum** [comment]
Thanks for the report. I've verified the same issue occurs with the default theme (i.e. CSS plugin disabled) so this is an upstream Obsidian issue. Please report this issue on the official forums.

**Comment by Grazfather** [comment]
Oh, strange, you're right, I don't know how I didn't notice until I installed this theme.

**Comment by Grazfather** [comment]
Looks like it was already reported :) https://forum.obsidian.md/t/the-vim-block-cursor-renders-behind-inline-code/1336
