### ISSUE TITLE
amoled dark snippet

### ISSUE THREAD

**Issue by rsubr** [insanum/obsidian_gruvbox#41]
Thanks for this great theme!

For AMOLED screens, this theme looks evern better when background is set to full black and it's also much easier on the eyes.

This [gruvbox-dark-amoled.txt](https://github.com/insanum/obsidian_gruvbox/files/10831131/gruvbox-dark-amoled.txt) CSS snippet sets the background to black.

To use this, save the attached file to your vault in .obsidian/snippets/gruvbox-dark-amoled.css (pls rename the attached .txt file to .css). Then go to Settings > Appearance > gruvbox-dark-amoled (ensure this is enabled).

Thanks again for Gruvbox :-)

**Comment by insanum** [comment]
Unless there is a way for the theme to know the display is amoled, there really isn't anything to change.
The best thing to do is keep this as a custom CSS snippet in your vault.
