### ISSUE TITLE
Tables in edit mode shadow selection highlighting

### ISSUE THREAD

**Issue by rklasen** [insanum/obsidian_gruvbox#5]
Hi,

when a table open in edit mode, selection highlighting is not working. I think it's because the table grey is rendered in front of selection highlighting.

**Comment by insanum** [comment]
Thanks for this report. This has been fixed. :-)

**Comment by rklasen** [comment]
Thank you, it worked great!

However I just notices, the same issue is present in single quotes for code: \`code here\`

**Comment by insanum** [comment]
I don't have this issue. Can you post a screenshot?

![Screen Shot 2020-10-26 at 9 50 29 AM](https://user-images.githubusercontent.com/515747/97202350-b7a8c880-1770-11eb-8f2e-8d1940b35470.png)

**Comment by rklasen** [comment]
Hi, thanks for the quick reply. It happens only in edit mode, not preview:

![image](https://user-images.githubusercontent.com/13201731/97213329-c075ba80-17c1-11eb-88ed-91b735e1876c.png)

**Comment by insanum** [comment]
Ah ok. I understand. So I tested this and see the same problem occurs with the default Obsidian theme. I suggest filing a bug on the forums.

**Comment by rklasen** [comment]
Understood, will do. Thanks again for the theme!
