### ISSUE TITLE
Certain emoji do not render correctly

### ISSUE THREAD

**Issue by brimwats** [insanum/obsidian_gruvbox#7]
Hello!

Using windows 10 and the latest version of the theme.

The emojis 0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣ do not render properly on the theme, either in edit or markdown mode:

![image](https://user-images.githubusercontent.com/49103046/98669282-096f5800-2306-11eb-9cea-48c54a0282e5.png)

**Comment by insanum** [comment]
This isn't a problem with this theme. The same issue is seen with the default theme in Obsidian. Can you report this problem on discord or the forums?

**Comment by brimwats** [comment]
will do!
