### ISSUE TITLE
Mermaid flow chat note show problem

### ISSUE THREAD

**Issue by loseblue** [insanum/obsidian_gruvbox#8]
Thank you for your obsidian_gruvbox ! IT's great!

I found a little show issue:
In Mermaid flow chat,  note show problem. 

```
\```mermaid
sequenceDiagram
    participant aa
    aa ->> bb :  11
    note over bb : SHOW Problem
\```
````

![image](https://user-images.githubusercontent.com/1415040/99038770-05bb2a00-25c1-11eb-9b1e-25a623213522.png)

**Comment by insanum** [comment]
Thanks for the report. This has been fixed.
