### ISSUE TITLE
Could You Please Tell Me How To Change Font?

### ISSUE THREAD

**Issue by ysl970629** [insanum/obsidian_gruvbox#9]
I want to change the font.

**Comment by insanum** [comment]
Font style:
https://github.com/insanum/obsidian_gruvbox/blob/a64d8924a8fbd96fba7ae8f25fa9396daeacee5f/obsidian.css#L49

Font size:
https://github.com/insanum/obsidian_gruvbox/blob/a64d8924a8fbd96fba7ae8f25fa9396daeacee5f/obsidian.css#L140
